# Generated by Django 2.2 on 2019-07-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='E-Book', editable=False, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('source_file', models.FileField(upload_to='')),
                ('epub_file', models.FileField(upload_to='')),
                ('mobi_file', models.FileField(upload_to='')),
                ('cover_file', models.FileField(upload_to='')),
            ],
        ),
    ]
