# Generated by Django 2.2 on 2019-07-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book115x18Fnsku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='11,5x18 FNSKU Book', editable=False, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('cover_pdf_file', models.FileField(upload_to='')),
                ('cover_psd_file', models.FileField(upload_to='')),
                ('pdf_file', models.FileField(upload_to='')),
                ('indesign_file', models.FileField(upload_to='')),
                ('pdf_old_version_file', models.FileField(upload_to='')),
                ('barcode_file', models.FileField(upload_to='')),
                ('cover_interiour_pdf', models.FileField(upload_to='')),
                ('cover_interiour_psd', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book115x18Isbn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='11,5x18 ISBN Book', editable=False, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('cover_pdf_file', models.FileField(upload_to='')),
                ('cover_psd_file', models.FileField(upload_to='')),
                ('pdf_file', models.FileField(upload_to='')),
                ('indesign_file', models.FileField(upload_to='')),
                ('pdf_old_version_file', models.FileField(upload_to='')),
                ('barcode_file', models.FileField(upload_to='')),
                ('cover_interiour_pdf', models.FileField(upload_to='')),
                ('cover_interiour_psd', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book125x19Fnsku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='12,5x19 FNSKU Book', editable=False, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('cover_pdf_file', models.FileField(upload_to='')),
                ('cover_psd_file', models.FileField(upload_to='')),
                ('pdf_file', models.FileField(upload_to='')),
                ('indesign_file', models.FileField(upload_to='')),
                ('pdf_old_version_file', models.FileField(upload_to='')),
                ('barcode_file', models.FileField(upload_to='')),
                ('cover_interiour_pdf', models.FileField(upload_to='')),
                ('cover_interiour_psd', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book125x19Hardcover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='12,5x19 Hardcover Book', editable=False, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('cover_pdf_file', models.FileField(upload_to='')),
                ('cover_psd_file', models.FileField(upload_to='')),
                ('pdf_file', models.FileField(upload_to='')),
                ('indesign_file', models.FileField(upload_to='')),
                ('pdf_old_version_file', models.FileField(upload_to='')),
                ('barcode_file', models.FileField(upload_to='')),
                ('cover_interiour_pdf', models.FileField(upload_to='')),
                ('cover_interiour_psd', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book125x19Isbn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='12,5x19 ISBN Book', editable=False, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('cover_pdf_file', models.FileField(upload_to='')),
                ('cover_psd_file', models.FileField(upload_to='')),
                ('pdf_file', models.FileField(upload_to='')),
                ('indesign_file', models.FileField(upload_to='')),
                ('pdf_old_version_file', models.FileField(upload_to='')),
                ('barcode_file', models.FileField(upload_to='')),
                ('cover_interiour_pdf', models.FileField(upload_to='')),
                ('cover_interiour_psd', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book5x8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='5x8 Book', editable=False, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('cover_pdf_file', models.FileField(upload_to='')),
                ('cover_psd_file', models.FileField(upload_to='')),
                ('pdf_file', models.FileField(upload_to='')),
                ('indesign_file', models.FileField(upload_to='')),
                ('pdf_old_version_file', models.FileField(upload_to='')),
                ('barcode_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BookA5Hardcover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A5 Hardcover Book', editable=False, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('cover_pdf_file', models.FileField(upload_to='')),
                ('cover_psd_file', models.FileField(upload_to='')),
                ('pdf_file', models.FileField(upload_to='')),
                ('indesign_file', models.FileField(upload_to='')),
                ('pdf_old_version_file', models.FileField(upload_to='')),
                ('barcode_file', models.FileField(upload_to='')),
                ('cover_interiour_pdf', models.FileField(upload_to='')),
                ('cover_interiour_psd', models.FileField(upload_to='')),
            ],
        ),
    ]
