# Generated by Django 2.2 on 2019-08-02 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0002_book115x18fnsku_book115x18isbn_book125x19fnsku_book125x19hardcover_book125x19isbn_book5x8_booka5hard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
