# Generated by Django 2.2 on 2019-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0004_auto_20190802_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
