# Generated by Django 2.2 on 2019-08-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0009_auto_20190808_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover_file',
            field=models.FileField(upload_to='E-Book'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='epub_file',
            field=models.FileField(upload_to='E-Book'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='mobi_file',
            field=models.FileField(upload_to='E-Book'),
        ),
    ]
