# Generated by Django 2.2 on 2019-08-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0010_auto_20190808_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='epub_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='mobi_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='source_file',
            field=models.FileField(upload_to=''),
        ),
    ]
