# Generated by Django 2.2 on 2019-08-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_delete_ebook'),
        ('uploaded_books', '0013_auto_20190816_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booka5hardcover',
            name='id',
        ),
        migrations.RemoveField(
            model_name='booka5hardcover',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='booka5hardcover',
            name='title',
        ),
        migrations.RemoveField(
            model_name='booka5hardcover',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='booka5hardcover',
            name='book_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Book'),
            preserve_default=False,
        ),
    ]
