# Generated by Django 2.2 on 2019-08-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0015_auto_20190816_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='epub_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='mobi_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='source_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
