# Generated by Django 2.2 on 2019-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0016_auto_20190819_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book115x18fnsku',
            name='barcode_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18fnsku',
            name='cover_interiour_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18fnsku',
            name='cover_interiour_psd',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18fnsku',
            name='cover_pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18fnsku',
            name='cover_psd_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18fnsku',
            name='indesign_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18fnsku',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18fnsku',
            name='pdf_old_version_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18isbn',
            name='barcode_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18isbn',
            name='cover_interiour_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18isbn',
            name='cover_interiour_psd',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18isbn',
            name='cover_pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18isbn',
            name='cover_psd_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18isbn',
            name='indesign_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18isbn',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book115x18isbn',
            name='pdf_old_version_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19fnsku',
            name='barcode_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19fnsku',
            name='cover_interiour_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19fnsku',
            name='cover_interiour_psd',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19fnsku',
            name='cover_pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19fnsku',
            name='cover_psd_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19fnsku',
            name='indesign_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19fnsku',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19fnsku',
            name='pdf_old_version_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='barcode_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='cover_interiour_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='cover_interiour_psd',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='cover_pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='cover_psd_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='indesign_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='pdf_old_version_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19isbn',
            name='barcode_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19isbn',
            name='cover_interiour_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19isbn',
            name='cover_interiour_psd',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19isbn',
            name='cover_pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19isbn',
            name='cover_psd_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19isbn',
            name='indesign_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19isbn',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book125x19isbn',
            name='pdf_old_version_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book5x8',
            name='barcode_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book5x8',
            name='cover_pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book5x8',
            name='cover_psd_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book5x8',
            name='indesign_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book5x8',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book5x8',
            name='pdf_old_version_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booka5hardcover',
            name='barcode_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booka5hardcover',
            name='cover_interiour_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booka5hardcover',
            name='cover_interiour_psd',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booka5hardcover',
            name='cover_pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booka5hardcover',
            name='cover_psd_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booka5hardcover',
            name='indesign_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booka5hardcover',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booka5hardcover',
            name='pdf_old_version_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
