# Generated by Django 2.2 on 2019-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0017_auto_20190819_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='source_file',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/no-file/no-file.png', upload_to=''),
        ),
    ]
