# Generated by Django 2.2 on 2019-08-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0019_auto_20190820_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='source_file',
            field=models.FileField(blank=True, default='no-file/no-file.png', upload_to=''),
        ),
    ]
