# Generated by Django 2.2 on 2019-08-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0020_auto_20190820_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='source_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
