# Generated by Django 2.2 on 2019-08-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_remove_book_ebook'),
        ('uploaded_books', '0025_auto_20190827_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='book',
        ),
        migrations.AddField(
            model_name='ebook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
