# Generated by Django 2.2 on 2019-08-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0026_auto_20190827_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='book',
        ),
    ]
