# Generated by Django 2.2 on 2019-08-29 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0028_auto_20190828_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='book5x8',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book5x8',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
