# Generated by Django 2.2 on 2019-12-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0030_auto_20190830_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book125x19hardcover',
            name='name',
            field=models.CharField(default='12,5x19 KDP TB ISBN Book', editable=False, max_length=50),
        ),
    ]
