# Generated by Django 2.2 on 2019-05-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190509_0934'),
        ('books', '0011_auto_20190507_2216'),
    ]

    operations = [
    ]
