# Generated by Django 2.2 on 2019-05-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20190513_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_author_email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
