# Generated by Django 2.2 on 2019-05-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20190513_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_author_email',
            field=models.CharField(max_length=100),
        ),
    ]
