# Generated by Django 2.2 on 2019-05-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20190513_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='co_author_email',
        ),
    ]
