# Generated by Django 2.2 on 2019-05-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_remove_book_co_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comparible',
        ),
    ]
