# Generated by Django 2.2 on 2019-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_remove_book_comparible'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comparible',
            field=models.URLField(default=1.0),
            preserve_default=False,
        ),
    ]
