# Generated by Django 2.2 on 2019-08-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_bookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
