# Generated by Django 2.2 on 2019-08-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20190816_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EBook',
        ),
    ]
