# Generated by Django 2.2 on 2019-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_delete_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='working_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
