# Generated by Django 2.2 on 2019-08-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20190819_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='co_author_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='co_author_name',
            field=models.ManyToManyField(blank=True, related_name='co_author', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='comparible',
            field=models.URLField(blank=True),
        ),
    ]
