# Generated by Django 2.2 on 2019-08-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0022_auto_20190827_0816'),
        ('books', '0033_auto_20190827_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ebook',
        ),
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploaded_books.EBook'),
        ),
    ]
