# Generated by Django 2.2 on 2019-08-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_auto_20190827_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ebook',
        ),
    ]
