# Generated by Django 2.2 on 2019-08-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0027_remove_ebook_book'),
        ('books', '0035_remove_book_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploaded_books.EBook'),
        ),
    ]
