# Generated by Django 2.2 on 2019-08-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0029_auto_20190829_0947'),
        ('books', '0037_auto_20190828_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book5x8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploaded_books.Book5x8'),
        ),
    ]
