# Generated by Django 2.2 on 2019-08-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_books', '0029_auto_20190829_0947'),
        ('books', '0038_book_book5x8'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_115x18_fnsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploaded_books.Book115x18Fnsku'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_115x18_isbn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploaded_books.Book115x18Isbn'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_125x19_fnsku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploaded_books.Book125x19Fnsku'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_125x19_hardcover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploaded_books.Book125x19Hardcover'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_125x19_isbn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploaded_books.Book125x19Isbn'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_A5_Hardcover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploaded_books.BookA5Hardcover'),
        ),
    ]
