# Generated by Django 2.2 on 2019-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_auto_20190830_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='working_number',
            field=models.CharField(max_length=12),
        ),
    ]
