# Generated by Django 2.2 on 2019-10-07 08:18

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0043_auto_20191007_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='working_number',
            field=models.CharField(max_length=12, validators=[books.validators.validate_underscore]),
        ),
    ]
