# Generated by Django 2.2 on 2019-11-17 10:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0048_auto_20191117_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_author_instructions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
