# Generated by Django 2.2 on 2019-11-20 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0049_auto_20191117_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_author_instructions',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
